spring.application.name=Candidat
#config
spring.cloud.config.import-check.enabled=true
spring.cloud.config.fail-fast=true
spring.config.import=optional:configserver:http://config-server:8099
server.port=8081

spring.h2.console.enabled=true
spring.h2.console.path=/h2
# Datasource
spring.datasource.username=Oumeima
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./Database/Data/Candidat;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://eureka:8761/eureka


# Spring RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
